[2021-06-03 12:40:05 +0000] [69757] [INFO] Starting gunicorn 20.1.0
[2021-06-03 12:40:05 +0000] [69757] [INFO] Listening at: http://0.0.0.0:8000 (69757)
[2021-06-03 12:40:05 +0000] [69757] [INFO] Using worker: sync
[2021-06-03 12:40:05 +0000] [69758] [INFO] Booting worker with pid: 69758
Not Found: /data/station.json
Not Found: /data/station.json
Unauthorized: /users/userinfo
Unauthorized: /taxis/reviews
Unauthorized: /taxis/reviews
Unauthorized: /orders
Unauthorized: /orders
Internal Server Error: /orders
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/20-2nd-WattaTaxi-backend/decorators.py", line 49, in wrapper
    return func(self, request, *args, **kwargs)
  File "/home/ubuntu/20-2nd-WattaTaxi-backend/orders/views.py", line 28, in post
    if passenger_number > Schedule.objects.get(id=schedule_id).seat_remain:
TypeError: '>' not supported between instances of 'str' and 'int'
[2021-06-03 13:25:49 +0000] [69757] [INFO] Handling signal: term
[2021-06-03 22:25:49 +0900] [69758] [INFO] Worker exiting (pid: 69758)
[2021-06-03 13:25:49 +0000] [69757] [INFO] Shutting down: Master
[2021-06-03 13:53:40 +0000] [70216] [INFO] Starting gunicorn 20.1.0
[2021-06-03 13:53:40 +0000] [70216] [INFO] Listening at: http://0.0.0.0:8000 (70216)
[2021-06-03 13:53:40 +0000] [70216] [INFO] Using worker: sync
[2021-06-03 13:53:40 +0000] [70217] [INFO] Booting worker with pid: 70217
[2021-06-03 13:58:00 +0000] [70216] [INFO] Handling signal: term
[2021-06-03 22:58:00 +0900] [70217] [INFO] Worker exiting (pid: 70217)
[2021-06-03 13:58:00 +0000] [70216] [INFO] Shutting down: Master
[2021-06-03 14:00:26 +0000] [70251] [INFO] Starting gunicorn 20.1.0
[2021-06-03 14:00:26 +0000] [70251] [INFO] Listening at: http://0.0.0.0:8000 (70251)
[2021-06-03 14:00:26 +0000] [70251] [INFO] Using worker: sync
[2021-06-03 14:00:26 +0000] [70252] [INFO] Booting worker with pid: 70252
Not Found: /taxis/reviews1
Not Found: /taxis/reviews1
Not Found: /taxis/reviews1
Not Found: /
Unauthorized: /users/userinfo
Unauthorized: /users/userinfo
Unauthorized: /users/userinfo
Unauthorized: /users/userinfo
Unauthorized: /users/userinfo
[2021-06-03 18:18:36 +0000] [70251] [CRITICAL] WORKER TIMEOUT (pid:70252)
[2021-06-04 03:18:36 +0900] [70252] [INFO] Worker exiting (pid: 70252)
[2021-06-03 18:18:36 +0000] [70782] [INFO] Booting worker with pid: 70782
Not Found: /
Unauthorized: /orders
[2021-06-04 02:03:29 +0000] [70251] [INFO] Handling signal: term
[2021-06-04 11:03:29 +0900] [70782] [INFO] Worker exiting (pid: 70782)
[2021-06-04 02:03:29 +0000] [70251] [INFO] Shutting down: Master
[2021-06-04 02:03:30 +0000] [72199] [INFO] Starting gunicorn 20.1.0
[2021-06-04 02:03:30 +0000] [72199] [INFO] Listening at: http://0.0.0.0:8000 (72199)
[2021-06-04 02:03:30 +0000] [72199] [INFO] Using worker: sync
[2021-06-04 02:03:30 +0000] [72200] [INFO] Booting worker with pid: 72200
[2021-06-04 02:20:24 +0000] [72199] [CRITICAL] WORKER TIMEOUT (pid:72200)
[2021-06-04 11:20:24 +0900] [72200] [INFO] Worker exiting (pid: 72200)
[2021-06-04 02:20:25 +0000] [72258] [INFO] Booting worker with pid: 72258
Bad Request: /users/signup
[2021-06-04 02:21:06 +0000] [72199] [CRITICAL] WORKER TIMEOUT (pid:72258)
[2021-06-04 11:21:06 +0900] [72258] [INFO] Worker exiting (pid: 72258)
[2021-06-04 02:21:06 +0000] [72259] [INFO] Booting worker with pid: 72259
[2021-06-04 02:21:22 +0000] [72199] [INFO] Handling signal: term
[2021-06-04 11:21:22 +0900] [72259] [INFO] Worker exiting (pid: 72259)
[2021-06-04 02:21:22 +0000] [72199] [INFO] Shutting down: Master
[2021-06-04 03:09:51 +0000] [72874] [INFO] Starting gunicorn 20.1.0
[2021-06-04 03:09:51 +0000] [72874] [INFO] Listening at: http://0.0.0.0:8000 (72874)
[2021-06-04 03:09:51 +0000] [72874] [INFO] Using worker: sync
[2021-06-04 03:09:51 +0000] [72875] [INFO] Booting worker with pid: 72875
Unauthorized: /users/userinfo
Unauthorized: /users/userinfo
Unauthorized: /users/userinfo
Unauthorized: /taxis/reviews
Unauthorized: /users/userinfo
[2021-06-04 03:19:19 +0000] [73116] [INFO] Starting gunicorn 20.1.0
[2021-06-04 03:19:19 +0000] [73116] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2021-06-04 03:19:19 +0000] [73116] [ERROR] Retrying in 1 second.
[2021-06-04 03:19:20 +0000] [73116] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2021-06-04 03:19:20 +0000] [73116] [ERROR] Retrying in 1 second.
[2021-06-04 03:19:21 +0000] [73116] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2021-06-04 03:19:21 +0000] [73116] [ERROR] Retrying in 1 second.
[2021-06-04 03:19:22 +0000] [73116] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2021-06-04 03:19:22 +0000] [73116] [ERROR] Retrying in 1 second.
[2021-06-04 03:19:23 +0000] [73116] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2021-06-04 03:19:23 +0000] [73116] [ERROR] Retrying in 1 second.
[2021-06-04 03:19:24 +0000] [73116] [ERROR] Can't connect to ('0.0.0.0', 8000)
[2021-06-04 03:23:15 +0000] [72874] [INFO] Handling signal: term
[2021-06-04 12:23:16 +0900] [72875] [INFO] Worker exiting (pid: 72875)
[2021-06-04 03:23:16 +0000] [72874] [INFO] Shutting down: Master
[2021-06-04 03:24:55 +0000] [73319] [INFO] Starting gunicorn 20.1.0
[2021-06-04 03:24:55 +0000] [73319] [INFO] Listening at: http://0.0.0.0:8000 (73319)
[2021-06-04 03:24:55 +0000] [73319] [INFO] Using worker: sync
[2021-06-04 03:24:55 +0000] [73320] [INFO] Booting worker with pid: 73320
Internal Server Error: /taxis
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/20-2nd-WattaTaxi-backend/taxis/views.py", line 207, in get
    departure_date = datetime.datetime.strptime(departure_date_string, "%Y-%m-%d")
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d'
Internal Server Error: /orders
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/20-2nd-WattaTaxi-backend/decorators.py", line 49, in wrapper
    return func(self, request, *args, **kwargs)
  File "/home/ubuntu/20-2nd-WattaTaxi-backend/orders/views.py", line 22, in post
    coming_schedule_id = int(data.get('coming_schedule_id', None))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Internal Server Error: /orders
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/20-2nd-WattaTaxi-backend/decorators.py", line 49, in wrapper
    return func(self, request, *args, **kwargs)
  File "/home/ubuntu/20-2nd-WattaTaxi-backend/orders/views.py", line 22, in post
    coming_schedule_id = int(data.get('coming_schedule_id', None))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Internal Server Error: /orders
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/20-2nd-WattaTaxi-backend/decorators.py", line 49, in wrapper
    return func(self, request, *args, **kwargs)
  File "/home/ubuntu/20-2nd-WattaTaxi-backend/orders/views.py", line 22, in post
    coming_schedule_id = int(data.get('coming_schedule_id', None))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Internal Server Error: /taxis
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/20-2nd-WattaTaxi-backend/taxis/views.py", line 207, in get
    departure_date = datetime.datetime.strptime(departure_date_string, "%Y-%m-%d")
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d'
Internal Server Error: /orders
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/wattataxi/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/20-2nd-WattaTaxi-backend/decorators.py", line 49, in wrapper
    return func(self, request, *args, **kwargs)
  File "/home/ubuntu/20-2nd-WattaTaxi-backend/orders/views.py", line 22, in post
    coming_schedule_id = int(data.get('coming_schedule_id', None))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2021-06-04 03:30:22 +0000] [73319] [INFO] Handling signal: term
[2021-06-04 12:30:22 +0900] [73320] [INFO] Worker exiting (pid: 73320)
[2021-06-04 03:30:22 +0000] [73319] [INFO] Shutting down: Master
